version: '3.8'

services:
  knb-shell-debug:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: knb-shell:debug
    container_name: knb-shell-debug
    ports:
      - "8080:8080"   # Port de l'application
      - "40000:40000" # Port du débogueur Delve
    deploy:
      placement:
        constraints: [node.role == manager]
    environment:
      - PORT=8080
      - SERVICE_NAME=shell
      - CONSUL_ADDR=http://consul-server:8500 # Assurez-vous que consul tourne
      - GIN_MODE=debug
    networks:
      - public_net

networks:
  public_net:
    external: true
    name: public_net # <--- Force la connexion au réseau global existant
